# **–Ü–Ω—Å—Ç—Ä—É–∫—Ü—ñ—è —â–æ–¥–æ –ø–æ—Å–ª—ñ–¥–æ–≤–Ω–æ—Å—Ç—ñ —Å–∫–ª–∞–¥–∞–Ω–Ω—è –æ–ø–µ—Ä–∞—Ç–æ—Ä–∞ `SELECT` —É SQL**

–û–ø–µ—Ä–∞—Ç–æ—Ä `SELECT` —É SQL –≤–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É—î—Ç—å—Å—è –¥–ª—è –≤–∏–±–æ—Ä—É –¥–∞–Ω–∏—Ö —ñ–∑ –±–∞–∑–∏ –¥–∞–Ω–∏—Ö. –í—ñ–Ω –¥–æ–∑–≤–æ–ª—è—î –≤–∏–±–∏—Ä–∞—Ç–∏, —Ñ—ñ–ª—å—Ç—Ä—É–≤–∞—Ç–∏, —Å–æ—Ä—Ç—É–≤–∞—Ç–∏ —Ç–∞ –≥—Ä—É–ø—É–≤–∞—Ç–∏ –¥–∞–Ω—ñ, –æ—Ç—Ä–∏–º—É—é—á–∏ –Ω–µ–æ–±—Ö—ñ–¥–Ω—É —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—é.

## **1. –ë–∞–∑–æ–≤–∏–π —Å–∏–Ω—Ç–∞–∫—Å–∏—Å `SELECT`**
```sql
SELECT [—Å—Ç–æ–≤–ø—Ü—ñ]
FROM [—Ç–∞–±–ª–∏—Ü—è]
WHERE [—É–º–æ–≤–∏]
GROUP BY [—Å—Ç–æ–≤–ø—Ü—ñ]
HAVING [—É–º–æ–≤–∏ –¥–ª—è –≥—Ä—É–ø]
ORDER BY [—Å—Ç–æ–≤–ø—Ü—ñ] [ASC|DESC]
LIMIT [–∫—ñ–ª—å–∫—ñ—Å—Ç—å —Ä—è–¥–∫—ñ–≤];
```
---

## **2. –ü–æ—Å–ª—ñ–¥–æ–≤–Ω—ñ—Å—Ç—å —Å–∫–ª–∞–¥–∞–Ω–Ω—è –æ–ø–µ—Ä–∞—Ç–æ—Ä–∞ `SELECT`**

### **–ö–†–û–ö 1: –í–∏–∑–Ω–∞—á–∏—Ç–∏ —Ç–∞–±–ª–∏—Ü—é, –∑ —è–∫–æ—ó –ø–æ—Ç—Ä—ñ–±–Ω–æ –≤–∏–±—Ä–∞—Ç–∏ –¥–∞–Ω—ñ**
–£ SQL –±—É–¥—å-—è–∫–∏–π –∑–∞–ø–∏—Ç –ø–æ—á–∏–Ω–∞—î—Ç—å—Å—è –∑ –≤–∫–∞–∑–∞–Ω–Ω—è –¥–∂–µ—Ä–µ–ª–∞ –¥–∞–Ω–∏—Ö.

üìå **–ü—Ä–∏–∫–ª–∞–¥**:  
```sql
SELECT * FROM Personnel;
```
–í–∏–≤–µ–¥–µ –≤—Å—ñ –∑–∞–ø–∏—Å–∏ –∑ —Ç–∞–±–ª–∏—Ü—ñ `Personnel`.

---

### **–ö–†–û–ö 2: –í–∏–∑–Ω–∞—á–∏—Ç–∏ –Ω–µ–æ–±—Ö—ñ–¥–Ω—ñ —Å—Ç–æ–≤–ø—Ü—ñ**
–Ø–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –≤–∏–±—Ä–∞—Ç–∏ —Ç—ñ–ª—å–∫–∏ –ø–µ–≤–Ω—ñ —Å—Ç–æ–≤–ø—Ü—ñ, –≤–∫–∞–∑—É—î–º–æ —ó—Ö –ø—ñ—Å–ª—è `SELECT`:
```sql
SELECT full_name, rank FROM Personnel;
```

> **–ü—Ä–∏–º—ñ—Ç–∫–∞**: –£–Ω–∏–∫–Ω–µ–Ω–Ω—è `SELECT *` —î –≥–∞—Ä–Ω–æ—é –ø—Ä–∞–∫—Ç–∏–∫–æ—é, –æ—Å–∫—ñ–ª—å–∫–∏ –≤–∏–±—ñ—Ä –ª–∏—à–µ –ø–æ—Ç—Ä—ñ–±–Ω–∏—Ö —Å—Ç–æ–≤–ø—Ü—ñ–≤ –∑–º–µ–Ω—à—É—î –Ω–∞–≤–∞–Ω—Ç–∞–∂–µ–Ω–Ω—è –Ω–∞ —Å–∏—Å—Ç–µ–º—É.

---

### **–ö–†–û–ö 3: –î–æ–¥–∞—Ç–∏ —Ñ—ñ–ª—å—Ç—Ä–∞—Ü—ñ—é –∑–∞ –¥–æ–ø–æ–º–æ–≥–æ—é `WHERE`**
–Ø–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –≤–∏–±—Ä–∞—Ç–∏ –¥–∞–Ω—ñ, —â–æ –≤—ñ–¥–ø–æ–≤—ñ–¥–∞—é—Ç—å –ø–µ–≤–Ω–∏–º —É–º–æ–≤–∞–º, –¥–æ–¥–∞—î–º–æ `WHERE`:

üìå **–ü—Ä–∏–∫–ª–∞–¥: –í–∏–±—Ä–∞—Ç–∏ –≤—Å—ñ—Ö –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö –∑—ñ –∑–≤–∞–Ω–Ω—è–º "–ö–∞–ø—ñ—Ç–∞–Ω"**
```sql
SELECT full_name, rank FROM Personnel WHERE rank = '–ö–∞–ø—ñ—Ç–∞–Ω';
```

üìå **–ü—Ä–∏–∫–ª–∞–¥: –í–∏–±—Ä–∞—Ç–∏ –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö —ñ–∑ –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—É "–ë–∞—Ç–∞–ª—å–π–æ–Ω A" —Ç–∞ –∑–≤–∞–Ω–Ω—è–º –Ω–µ –Ω–∏–∂—á–µ "–ú–∞–π–æ—Ä"**
```sql
SELECT full_name, rank FROM Personnel WHERE unit = '–ë–∞—Ç–∞–ª—å–π–æ–Ω A' AND rank >= '–ú–∞–π–æ—Ä';
```

> **–û–ø–µ—Ä–∞—Ç–æ—Ä–∏ –ø–æ—Ä—ñ–≤–Ω—è–Ω–Ω—è:**  
`=` (–¥–æ—Ä—ñ–≤–Ω—é—î), `!=` (–Ω–µ –¥–æ—Ä—ñ–≤–Ω—é—î), `>` (–±—ñ–ª—å—à–µ), `<` (–º–µ–Ω—à–µ), `>=` (–±—ñ–ª—å—à–µ –∞–±–æ —Ä—ñ–≤–Ω–µ), `<=` (–º–µ–Ω—à–µ –∞–±–æ —Ä—ñ–≤–Ω–µ).

---

### **–ö–†–û–ö 4: –í–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è `JOIN` –¥–ª—è –æ–±‚Äô—î–¥–Ω–∞–Ω–Ω—è —Ç–∞–±–ª–∏—Ü—å**
–Ø–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –æ—Ç—Ä–∏–º–∞—Ç–∏ —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—é –∑ –∫—ñ–ª—å–∫–æ—Ö —Ç–∞–±–ª–∏—Ü—å, –≤–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É—î—Ç—å—Å—è `JOIN`.

üìå **–ü—Ä–∏–∫–ª–∞–¥: –û—Ç—Ä–∏–º–∞—Ç–∏ —Å–ø–∏—Å–æ–∫ –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö —Ä–∞–∑–æ–º —ñ–∑ —ó—Ö–Ω—ñ–º–∏ –∫—É—Ä—Å–∞–º–∏ –Ω–∞–≤—á–∞–Ω–Ω—è**
```sql
SELECT p.full_name, t.course_name
FROM Personnel p
JOIN Training t ON p.personnel_id = t.personnel_id;
```

> **–¢–∏–ø–∏ `JOIN`:**  
- `INNER JOIN` ‚Äì –ø–æ–≤–µ—Ä—Ç–∞—î –ª–∏—à–µ —Ç—ñ —Ä—è–¥–∫–∏, —è–∫—ñ –º–∞—é—Ç—å –≤—ñ–¥–ø–æ–≤—ñ–¥–Ω—ñ –∑–Ω–∞—á–µ–Ω–Ω—è –≤ –æ–±–æ—Ö —Ç–∞–±–ª–∏—Ü—è—Ö.
- `LEFT JOIN` ‚Äì –ø–æ–≤–µ—Ä—Ç–∞—î –≤—Å—ñ —Ä—è–¥–∫–∏ –∑ –ª—ñ–≤–æ—ó —Ç–∞–±–ª–∏—Ü—ñ —Ç–∞ –≤—ñ–¥–ø–æ–≤—ñ–¥–Ω—ñ –∑–Ω–∞—á–µ–Ω–Ω—è –∑ –ø—Ä–∞–≤–æ—ó.
- `RIGHT JOIN` ‚Äì –ø–æ–≤–µ—Ä—Ç–∞—î –≤—Å—ñ —Ä—è–¥–∫–∏ –∑ –ø—Ä–∞–≤–æ—ó —Ç–∞–±–ª–∏—Ü—ñ —Ç–∞ –≤—ñ–¥–ø–æ–≤—ñ–¥–Ω—ñ –∑–Ω–∞—á–µ–Ω–Ω—è –∑ –ª—ñ–≤–æ—ó.
- `FULL JOIN` ‚Äì –ø–æ–≤–µ—Ä—Ç–∞—î –≤—Å—ñ —Ä—è–¥–∫–∏ –∑ –æ–±–æ—Ö —Ç–∞–±–ª–∏—Ü—å.

---

### **–ö–†–û–ö 5: –ì—Ä—É–ø—É–≤–∞–Ω–Ω—è –¥–∞–Ω–∏—Ö –∑–∞ –¥–æ–ø–æ–º–æ–≥–æ—é `GROUP BY`**
–Ø–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –∑–≥—Ä—É–ø—É–≤–∞—Ç–∏ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–∏, –≤–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É—î—Ç—å—Å—è `GROUP BY`.

üìå **–ü—Ä–∏–∫–ª–∞–¥: –ü—ñ–¥—Ä–∞—Ö—É–≤–∞—Ç–∏ –∫—ñ–ª—å–∫—ñ—Å—Ç—å –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö —É –∫–æ–∂–Ω–æ–º—É –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—ñ**
```sql
SELECT unit, COUNT(*) AS num_personnel FROM Personnel GROUP BY unit;
```

üìå **–ü—Ä–∏–∫–ª–∞–¥: –í–∏–∑–Ω–∞—á–∏—Ç–∏ —Å–µ—Ä–µ–¥–Ω—é —Ç—Ä–∏–≤–∞–ª—ñ—Å—Ç—å –∫—É—Ä—Å—ñ–≤**
```sql
SELECT instructor, AVG(end_date - start_date) AS avg_duration
FROM Training
GROUP BY instructor;
```

---

### **–ö–†–û–ö 6: –§—ñ–ª—å—Ç—Ä–∞—Ü—ñ—è –≥—Ä—É–ø –∑–∞ –¥–æ–ø–æ–º–æ–≥–æ—é `HAVING`**
–ù–∞ –≤—ñ–¥–º—ñ–Ω—É –≤—ñ–¥ `WHERE`, —è–∫–∏–π –ø—Ä–∞—Ü—é—î –ø–µ—Ä–µ–¥ –≥—Ä—É–ø—É–≤–∞–Ω–Ω—è–º, `HAVING` –≤–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É—î—Ç—å—Å—è –¥–ª—è —Ñ—ñ–ª—å—Ç—Ä–∞—Ü—ñ—ó –≤–∂–µ –∑–≥—Ä—É–ø–æ–≤–∞–Ω–∏—Ö –¥–∞–Ω–∏—Ö.

üìå **–ü—Ä–∏–∫–ª–∞–¥: –í—ñ–¥–æ–±—Ä–∞–∑–∏—Ç–∏ –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª–∏, –¥–µ –±—ñ–ª—å—à–µ 3 –≤—ñ–π—Å—å–∫–æ–≤–æ—Å–ª—É–∂–±–æ–≤—Ü—ñ–≤**
```sql
SELECT unit, COUNT(*) AS num_personnel
FROM Personnel
GROUP BY unit
HAVING COUNT(*) > 3;
```

---

### **–ö–†–û–ö 7: –°–æ—Ä—Ç—É–≤–∞–Ω–Ω—è —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ñ–≤ –∑–∞ –¥–æ–ø–æ–º–æ–≥–æ—é `ORDER BY`**
–î–∞–Ω—ñ –º–æ–∂–Ω–∞ –≤–ø–æ—Ä—è–¥–∫—É–≤–∞—Ç–∏ –∑–∞ –æ–¥–Ω–∏–º –∞–±–æ –∫—ñ–ª—å–∫–æ–º–∞ –ø–æ–ª—è–º–∏ —É –ø–æ—Ä—è–¥–∫—É –∑—Ä–æ—Å—Ç–∞–Ω–Ω—è (`ASC`, –∑–∞ –∑–∞–º–æ–≤—á—É–≤–∞–Ω–Ω—è–º) –∞–±–æ —Å–ø–∞–¥–∞–Ω–Ω—è (`DESC`).

üìå **–ü—Ä–∏–∫–ª–∞–¥: –°–æ—Ä—Ç—É–≤–∞—Ç–∏ —Å–ø–∏—Å–æ–∫ –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö –∑–∞ –∑–≤–∞–Ω–Ω—è–º —É –ø–æ—Ä—è–¥–∫—É —Å–ø–∞–¥–∞–Ω–Ω—è**
```sql
SELECT full_name, rank FROM Personnel ORDER BY rank DESC;
```

üìå **–ü—Ä–∏–∫–ª–∞–¥: –°–æ—Ä—Ç—É–≤–∞—Ç–∏ –∫—É—Ä—Å–∏ –∑–∞ –¥–∞—Ç–æ—é –ø–æ—á–∞—Ç–∫—É**
```sql
SELECT course_name, start_date FROM Training ORDER BY start_date ASC;
```

---

### **–ö–†–û–ö 8: –û–±–º–µ–∂–µ–Ω–Ω—è –∫—ñ–ª—å–∫–æ—Å—Ç—ñ —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ñ–≤ –∑–∞ –¥–æ–ø–æ–º–æ–≥–æ—é `LIMIT`**
–Ø–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –≤–∏–≤–µ—Å—Ç–∏ –ª–∏—à–µ –ø–µ—Ä—à—ñ –∫—ñ–ª—å–∫–∞ –∑–∞–ø–∏—Å—ñ–≤, –≤–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É—î—Ç—å—Å—è `LIMIT`.

üìå **–ü—Ä–∏–∫–ª–∞–¥: –û—Ç—Ä–∏–º–∞—Ç–∏ 5 –æ—Å—Ç–∞–Ω–Ω—ñ—Ö –∫—É—Ä—Å—ñ–≤**
```sql
SELECT * FROM Training ORDER BY start_date DESC LIMIT 5;
```

üìå **–ü—Ä–∏–∫–ª–∞–¥: –û—Ç—Ä–∏–º–∞—Ç–∏ 3 –Ω–∞–π—Å—Ç–∞—Ä—à–∏—Ö –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö (–∑–∞ –∑–≤–∞–Ω–Ω—è–º)**
```sql
SELECT full_name, rank FROM Personnel ORDER BY rank DESC LIMIT 3;
```

---

## **4. –ü—Ä–∏–∫–ª–∞–¥–∏ –∫–æ–º–ø–ª–µ–∫—Å–Ω–∏—Ö –∑–∞–ø–∏—Ç—ñ–≤**
üìå **–û—Ç—Ä–∏–º–∞—Ç–∏ —Å–ø–∏—Å–æ–∫ –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö —ñ–∑ –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—ñ–≤, –¥–µ –ø–æ–Ω–∞–¥ 5 –æ—Å—ñ–±, –≤—ñ–¥—Å–æ—Ä—Ç–æ–≤–∞–Ω–∏–π –∑–∞ –∑–≤–∞–Ω–Ω—è–º**
```sql
SELECT full_name, rank, unit
FROM Personnel
WHERE unit IN (SELECT unit FROM Personnel GROUP BY unit HAVING COUNT(*) > 5)
ORDER BY rank DESC;
```

üìå **–û—Ç—Ä–∏–º–∞—Ç–∏ –≤—Å—ñ—Ö –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö, —è–∫—ñ –Ω–µ –ø—Ä–æ—Ö–æ–¥–∏–ª–∏ –∂–æ–¥–Ω–æ–≥–æ –Ω–∞–≤—á–∞–Ω–Ω—è**
```sql
SELECT full_name FROM Personnel WHERE personnel_id NOT IN (SELECT personnel_id FROM Training);
```

üìå **–û—Ç—Ä–∏–º–∞—Ç–∏ —Å–µ—Ä–µ–¥–Ω—é —Ç—Ä–∏–≤–∞–ª—ñ—Å—Ç—å –∫—É—Ä—Å—ñ–≤ –¥–ª—è –∫–æ–∂–Ω–æ–≥–æ —ñ–Ω—Å—Ç—Ä—É–∫—Ç–æ—Ä–∞, –¥–µ —Å–µ—Ä–µ–¥–Ω—è —Ç—Ä–∏–≤–∞–ª—ñ—Å—Ç—å –±—ñ–ª—å—à–µ 7 –¥–Ω—ñ–≤**
```sql
SELECT instructor, AVG(end_date - start_date) AS avg_duration
FROM Training
GROUP BY instructor
HAVING AVG(end_date - start_date) > 7;
```

---

## **5. –í–∏—Å–Ω–æ–≤–∫–∏**
‚úÖ **–û—Å–Ω–æ–≤–Ω—ñ –ø—Ä–∞–≤–∏–ª–∞ —Å–∫–ª–∞–¥–∞–Ω–Ω—è `SELECT`-–∑–∞–ø–∏—Ç—É:**
1. –ü–æ—á–∏–Ω–∞–π—Ç–µ –∑ `SELECT` ‚Äì –≤–∏–∑–Ω–∞—á–µ–Ω–Ω—è –Ω–µ–æ–±—Ö—ñ–¥–Ω–∏—Ö —Å—Ç–æ–≤–ø—Ü—ñ–≤.
2. –í–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É–π—Ç–µ `FROM` –¥–ª—è –≤–∏–±–æ—Ä—É —Ç–∞–±–ª–∏—Ü—ñ.
3. –î–æ–¥–∞–≤–∞–π—Ç–µ `WHERE`, —è–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –≤—ñ–¥—Ñ—ñ–ª—å—Ç—Ä—É–≤–∞—Ç–∏ –¥–∞–Ω—ñ.
4. –í–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É–π—Ç–µ `JOIN`, —è–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –æ–±'—î–¥–Ω–∞—Ç–∏ –∫—ñ–ª—å–∫–∞ —Ç–∞–±–ª–∏—Ü—å.
5. –í–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É–π—Ç–µ `GROUP BY`, —è–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –∑–≥—Ä—É–ø—É–≤–∞—Ç–∏ –¥–∞–Ω—ñ.
6. –í–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É–π—Ç–µ `HAVING`, —è–∫—â–æ –ø–æ—Ç—Ä—ñ–±–Ω–æ –≤—ñ–¥—Ñ—ñ–ª—å—Ç—Ä—É–≤–∞—Ç–∏ –∑–≥—Ä—É–ø–æ–≤–∞–Ω—ñ –¥–∞–Ω—ñ.
7. –í–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É–π—Ç–µ `ORDER BY` –¥–ª—è —Å–æ—Ä—Ç—É–≤–∞–Ω–Ω—è.
8. –í–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É–π—Ç–µ `LIMIT` –¥–ª—è –æ–±–º–µ–∂–µ–Ω–Ω—è –∫—ñ–ª—å–∫–æ—Å—Ç—ñ –∑–∞–ø–∏—Å—ñ–≤.

üöÄ **–ö–ª—é—á–æ–≤–∏–π –º–µ—Å–µ–¥–∂**:  
**–ü–æ—Å–ª—ñ–¥–æ–≤–Ω—ñ—Å—Ç—å —Å–∫–ª–∞–¥–∞–Ω–Ω—è –æ–ø–µ—Ä–∞—Ç–æ—Ä–∞ `SELECT` –¥–æ–ø–æ–º–∞–≥–∞—î –µ—Ñ–µ–∫—Ç–∏–≤–Ω–æ –≤–∏–±–∏—Ä–∞—Ç–∏, —Ñ—ñ–ª—å—Ç—Ä—É–≤–∞—Ç–∏, —Å–æ—Ä—Ç—É–≤–∞—Ç–∏ —Ç–∞ –∞–Ω–∞–ª—ñ–∑—É–≤–∞—Ç–∏ —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—é –≤ –±–∞–∑–∞—Ö –¥–∞–Ω–∏—Ö. –ß—ñ—Ç–∫–µ –¥–æ—Ç—Ä–∏–º–∞–Ω–Ω—è –ø–æ—Ä—è–¥–∫—É –æ–ø–µ—Ä–∞—Ç–æ—Ä—ñ–≤ SQL –ø—ñ–¥–≤–∏—â—É—î –ø—Ä–æ–¥—É–∫—Ç–∏–≤–Ω—ñ—Å—Ç—å –∑–∞–ø–∏—Ç—ñ–≤ —Ç–∞ –æ–ø—Ç–∏–º—ñ–∑—É—î —Ä–æ–±–æ—Ç—É –∑ –≤–µ–ª–∏–∫–∏–º–∏ –Ω–∞–±–æ—Ä–∞–º–∏ –¥–∞–Ω–∏—Ö.**