# **–†–æ–∑—à–∏—Ä–µ–Ω–∏–π –ø–ª–∞–Ω-–∫–æ–Ω—Ç–µ–Ω—Ç –¥–ª—è –ø—Ä–æ–≤–µ–¥–µ–Ω–Ω—è –ª–µ–∫—Ü—ñ—ó**  
## **–¢–µ–º–∞ 2. –ó–∞–Ω—è—Ç—Ç—è 6. –û—Å–Ω–æ–≤–∏ –≤–∏–±–æ—Ä—É —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—ó –∑ –±–∞–∑ –¥–∞–Ω–∏—Ö. –ü–æ–Ω—è—Ç—Ç—è –ø—Ä–æ –Ω–µ—Ä–µ–ª—è—Ü—ñ–π–Ω—ñ –±–∞–∑–∏ –¥–∞–Ω–∏—Ö**  
### **1. –û—Å–Ω–æ–≤–∏ –≤–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è –∑–∞—Å–æ–±—ñ–≤ –≤–∏–±–æ—Ä—É —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—ó –∑ –±–∞–∑–∏ –¥–∞–Ω–∏—Ö**  
### **2. –ü–æ–Ω—è—Ç—Ç—è –ø—Ä–æ –Ω–µ—Ä–µ–ª—è—Ü—ñ–π–Ω—ñ –±–∞–∑–∏ –¥–∞–Ω–∏—Ö**  

---

## **1. –í—Å—Ç—É–ø (10 —Ö–≤)**  

### **1.1. –ú–µ—Ç–∞ –ª–µ–∫—Ü—ñ—ó**  
- –û–∑–Ω–∞–π–æ–º–∏—Ç–∏ —Å–ª—É—Ö–∞—á—ñ–≤ —ñ–∑ –∑–∞—Å–æ–±–∞–º–∏ –≤–∏–±–æ—Ä—É —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—ó —É —Ä–µ–ª—è—Ü—ñ–π–Ω–∏—Ö –±–∞–∑–∞—Ö –¥–∞–Ω–∏—Ö (PostgreSQL).  
- –ù–∞–≤—á–∏—Ç–∏ –≤–∏–∫–æ–Ω—É–≤–∞—Ç–∏ –∑–∞–ø–∏—Ç–∏ –≤–∏–±—ñ—Ä–∫–∏ –∑ –≤–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è–º SQL.  
- –ü–æ—è—Å–Ω–∏—Ç–∏ –≤—ñ–¥–º—ñ–Ω–Ω–æ—Å—Ç—ñ –º—ñ–∂ —Ä–µ–ª—è—Ü—ñ–π–Ω–∏–º–∏ —Ç–∞ –Ω–µ—Ä–µ–ª—è—Ü—ñ–π–Ω–∏–º–∏ –±–∞–∑–∞–º–∏ –¥–∞–Ω–∏—Ö.  
- –†–æ–∑–≥–ª—è–Ω—É—Ç–∏ –æ—Å–Ω–æ–≤–∏ —Ä–æ–±–æ—Ç–∏ –∑ –Ω–µ—Ä–µ–ª—è—Ü—ñ–π–Ω–∏–º–∏ –±–∞–∑–∞–º–∏, —Ç–∞–∫–∏–º–∏ —è–∫ MongoDB.  

### **1.2. –û—á—ñ–∫—É–≤–∞–Ω—ñ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–∏**  
–ü—ñ—Å–ª—è –ª–µ–∫—Ü—ñ—ó —Å–ª—É—Ö–∞—á—ñ –∑–º–æ–∂—É—Ç—å:  
‚úÖ –í–∏–∫–æ–Ω—É–≤–∞—Ç–∏ –≤–∏–±—ñ—Ä–∫—É –¥–∞–Ω–∏—Ö —É PostgreSQL.  
‚úÖ –í–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É–≤–∞—Ç–∏ SQL-–∑–∞–ø–∏—Ç–∏ –¥–ª—è —Ñ—ñ–ª—å—Ç—Ä–∞—Ü—ñ—ó —Ç–∞ —Å–æ—Ä—Ç—É–≤–∞–Ω–Ω—è —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—ó.  
‚úÖ –†–æ–∑—É–º—ñ—Ç–∏ –≤—ñ–¥–º—ñ–Ω–Ω–æ—Å—Ç—ñ –º—ñ–∂ —Ä–µ–ª—è—Ü—ñ–π–Ω–∏–º–∏ —Ç–∞ –Ω–µ—Ä–µ–ª—è—Ü—ñ–π–Ω–∏–º–∏ –±–∞–∑–∞–º–∏.  
‚úÖ –í–∏–∫–æ–Ω—É–≤–∞—Ç–∏ –±–∞–∑–æ–≤—ñ –∑–∞–ø–∏—Ç–∏ —É MongoDB.  

---

## **2. –û—Å–Ω–æ–≤–∏ –≤–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è –∑–∞—Å–æ–±—ñ–≤ –≤–∏–±–æ—Ä—É —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—ó –∑ –±–∞–∑–∏ –¥–∞–Ω–∏—Ö (60 —Ö–≤)**  

### **2.1. –û—Å–Ω–æ–≤–Ω—ñ –æ–ø–µ—Ä–∞—Ç–æ—Ä–∏ –≤–∏–±—ñ—Ä–∫–∏ —É SQL**  

üìå **–ë–∞–∑–æ–≤–∏–π –æ–ø–µ—Ä–∞—Ç–æ—Ä `SELECT`**  
```sql
SELECT * FROM Personnel;
```
üìå **–í–∏–±—ñ—Ä–∫–∞ –æ–∫—Ä–µ–º–∏—Ö —Å—Ç–æ–≤–ø—Ü—ñ–≤**  
```sql
SELECT full_name, rank FROM Personnel;
```
üìå **–§—ñ–ª—å—Ç—Ä–∞—Ü—ñ—è –¥–∞–Ω–∏—Ö –∑–∞ —É–º–æ–≤–∞–º–∏ (`WHERE`)**  
```sql
SELECT * FROM Personnel WHERE rank = '–ö–∞–ø—ñ—Ç–∞–Ω';
```
üìå **–°–æ—Ä—Ç—É–≤–∞–Ω–Ω—è (`ORDER BY`)**  
```sql
SELECT * FROM Personnel ORDER BY full_name ASC;
```

---

### **2.2. –í–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è `JOIN` –¥–ª—è –æ–±‚Äô—î–¥–Ω–∞–Ω–Ω—è —Ç–∞–±–ª–∏—Ü—å**  
üìå **–ü—Ä–∏–∫–ª–∞–¥ —Å—Ç—Ä—É–∫—Ç—É—Ä–∏ –±–∞–∑–∏ –¥–∞–Ω–∏—Ö**  

#### **–¢–∞–±–ª–∏—Ü—è `Personnel` (–û—Å–æ–±–æ–≤–∏–π —Å–∫–ª–∞–¥)**
| personnel_id | full_name | rank     | unit_id |
|-------------|-----------|---------|--------|
| 1           | –Ü–≤–∞–Ω –ü–µ—Ç—Ä–æ–≤  | –ö–∞–ø—ñ—Ç–∞–Ω  | 101    |
| 2           | –ê–Ω–¥—Ä—ñ–π –°–∏–¥–æ—Ä–µ–Ω–∫–æ | –õ–µ–π—Ç–µ–Ω–∞–Ω—Ç | 102    |

#### **–¢–∞–±–ª–∏—Ü—è `Units` (–ü—ñ–¥—Ä–æ–∑–¥—ñ–ª–∏)**
| unit_id | name         |
|---------|-------------|
| 101     | –ë–∞—Ç–∞–ª—å–π–æ–Ω A |
| 102     | –ë–∞—Ç–∞–ª—å–π–æ–Ω B |

üìå **–ü—Ä–∏–∫–ª–∞–¥ `INNER JOIN`**  
```sql
SELECT p.full_name, p.rank, u.name AS unit_name
FROM Personnel p
JOIN Units u ON p.unit_id = u.unit_id;
```

üìå **–ü—Ä–∏–∫–ª–∞–¥ `LEFT JOIN`** (–≤–∏–≤–æ–¥–∏—Ç—å –≤—Å—ñ—Ö –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö, –Ω–∞–≤—ñ—Ç—å —è–∫—â–æ –≤–æ–Ω–∏ –Ω–µ –∑–∞–∫—Ä—ñ–ø–ª–µ–Ω—ñ –∑–∞ –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª–æ–º)  
```sql
SELECT p.full_name, u.name AS unit_name
FROM Personnel p
LEFT JOIN Units u ON p.unit_id = u.unit_id;
```

---

### **2.3. –í–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è –∞–≥—Ä–µ–≥–∞—Ç–Ω–∏—Ö —Ñ—É–Ω–∫—Ü—ñ–π**
üìå **–ü—ñ–¥—Ä–∞—Ö—É–Ω–æ–∫ –∫—ñ–ª—å–∫–æ—Å—Ç—ñ –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö —É –∫–æ–∂–Ω–æ–º—É –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—ñ**  
```sql
SELECT u.name AS unit_name, COUNT(p.personnel_id) AS num_personnel
FROM Units u
LEFT JOIN Personnel p ON u.unit_id = p.unit_id
GROUP BY u.name;
```
üìå **–°–µ—Ä–µ–¥–Ω—ñ–π —Ä—ñ–≤–µ–Ω—å –ø—ñ–¥–≥–æ—Ç–æ–≤–∫–∏ –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö —É –∫–æ–∂–Ω–æ–º—É –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—ñ**  
```sql
SELECT unit_id, AVG(training_level) AS avg_training
FROM Personnel
GROUP BY unit_id;
```

---

### **2.4. –ü—ñ–¥–∑–∞–ø–∏—Ç–∏ —É SQL**  
üìå **–í–∏–±—ñ—Ä–∫–∞ –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö, —è–∫—ñ —Å–ª—É–∂–∞—Ç—å —É –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—ñ –∑ –Ω–∞–π–±—ñ–ª—å—à–æ—é –∫—ñ–ª—å–∫—ñ—Å—Ç—é –æ—Å–æ–±–æ–≤–æ–≥–æ —Å–∫–ª–∞–¥—É**  
```sql
SELECT full_name, rank
FROM Personnel
WHERE unit_id = (SELECT unit_id FROM Personnel GROUP BY unit_id ORDER BY COUNT(*) DESC LIMIT 1);
```

---

## **3. –ü–æ–Ω—è—Ç—Ç—è –ø—Ä–æ –Ω–µ—Ä–µ–ª—è—Ü—ñ–π–Ω—ñ –±–∞–∑–∏ –¥–∞–Ω–∏—Ö (40 —Ö–≤)**  

### **3.1. –í—ñ–¥–º—ñ–Ω–Ω–æ—Å—Ç—ñ –º—ñ–∂ —Ä–µ–ª—è—Ü—ñ–π–Ω–∏–º–∏ —Ç–∞ –Ω–µ—Ä–µ–ª—è—Ü—ñ–π–Ω–∏–º–∏ –ë–î**  
üìå **–û—Å–Ω–æ–≤–Ω—ñ –≤—ñ–¥–º—ñ–Ω–Ω–æ—Å—Ç—ñ**  

| –ü–∞—Ä–∞–º–µ—Ç—Ä           | –†–µ–ª—è—Ü—ñ–π–Ω—ñ –ë–î (PostgreSQL) | –ù–µ—Ä–µ–ª—è—Ü—ñ–π–Ω—ñ –ë–î (MongoDB) |
|--------------------|------------------------|------------------------|
| –°—Ç—Ä—É–∫—Ç—É—Ä–∞         | –¢–∞–±–ª–∏—Ü—ñ (—Ä—è–¥–∫–∏, —Å—Ç–æ–≤–ø—Ü—ñ) | –î–æ–∫—É–º–µ–Ω—Ç–∏ (JSON-–ø–æ–¥—ñ–±–Ω—ñ –æ–±'—î–∫—Ç–∏) |
| –ì–Ω—É—á–∫—ñ—Å—Ç—å         | –§—ñ–∫—Å–æ–≤–∞–Ω–∞ —Å—Ö–µ–º–∞          | –î–∏–Ω–∞–º—ñ—á–Ω–∞ —Å—Ö–µ–º–∞ |
| –ú–∞—Å—à—Ç–∞–±–æ–≤–∞–Ω—ñ—Å—Ç—å   | –í–µ—Ä—Ç–∏–∫–∞–ª—å–Ω–∞              | –ì–æ—Ä–∏–∑–æ–Ω—Ç–∞–ª—å–Ω–∞ |
| –¢–∏–ø–æ–≤—ñ —Å—Ü–µ–Ω–∞—Ä—ñ—ó –≤–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è | –§—ñ–Ω–∞–Ω—Å–∏, –≤—ñ–π—Å—å–∫–æ–≤–∞ –∞–Ω–∞–ª—ñ—Ç–∏–∫–∞ | –ê–Ω–∞–ª—ñ–∑ –≤–µ–ª–∏–∫–∏—Ö –¥–∞–Ω–∏—Ö, –≤–µ–±-–¥–æ–¥–∞—Ç–∫–∏ |

---

### **3.2. –û—Å–Ω–æ–≤–∏ —Ä–æ–±–æ—Ç–∏ –∑ MongoDB**  

üìå **–ü—Ä–∏–∫–ª–∞–¥ —Å—Ç—Ä—É–∫—Ç—É—Ä–∏ –¥–æ–∫—É–º–µ–Ω—Ç–∞ —É MongoDB**  
```json
{
  "personnel_id": 1,
  "full_name": "–Ü–≤–∞–Ω –ü–µ—Ç—Ä–æ–≤",
  "rank": "–ö–∞–ø—ñ—Ç–∞–Ω",
  "unit": {
    "unit_id": 101,
    "name": "–ë–∞—Ç–∞–ª—å–π–æ–Ω A"
  }
}
```

üìå **–ë–∞–∑–æ–≤—ñ –∫–æ–º–∞–Ω–¥–∏ MongoDB**  
**–°—Ç–≤–æ—Ä–µ–Ω–Ω—è –±–∞–∑–∏ –¥–∞–Ω–∏—Ö:**  
```javascript
use military_db
```
**–î–æ–¥–∞–≤–∞–Ω–Ω—è –¥–æ–∫—É–º–µ–Ω—Ç–∞:**  
```javascript
db.personnel.insertOne({
  "personnel_id": 1,
  "full_name": "–Ü–≤–∞–Ω –ü–µ—Ç—Ä–æ–≤",
  "rank": "–ö–∞–ø—ñ—Ç–∞–Ω",
  "unit_id": 101
});
```
**–í–∏–±—ñ—Ä–∫–∞ –≤—Å—ñ—Ö –¥–æ–∫—É–º–µ–Ω—Ç—ñ–≤:**  
```javascript
db.personnel.find()
```
**–§—ñ–ª—å—Ç—Ä–∞—Ü—ñ—è –∑–∞ –∑–≤–∞–Ω–Ω—è–º:**  
```javascript
db.personnel.find({ "rank": "–ö–∞–ø—ñ—Ç–∞–Ω" })
```

---

### **3.3. –ü–æ—Ä—ñ–≤–Ω—è–Ω–Ω—è SQL —Ç–∞ NoSQL —É –≤–∏–±—ñ—Ä—Ü—ñ –¥–∞–Ω–∏—Ö**
üìå **SQL (PostgreSQL)**  
```sql
SELECT full_name, rank FROM Personnel WHERE rank = '–ö–∞–ø—ñ—Ç–∞–Ω';
```
üìå **MongoDB (NoSQL)**  
```javascript
db.personnel.find({ "rank": "–ö–∞–ø—ñ—Ç–∞–Ω" })
```

---

## **4. –ü—Ä–∞–∫—Ç–∏—á–Ω—ñ –∑–∞–≤–¥–∞–Ω–Ω—è (30 —Ö–≤)**  
‚úÖ **–ó–∞–≤–¥–∞–Ω–Ω—è 1:** –í–∏–∫–æ–Ω–∞—Ç–∏ SQL-–∑–∞–ø–∏—Ç –¥–ª—è –≤–∏–≤–µ–¥–µ–Ω–Ω—è —Å–ø–∏—Å–∫—É –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö —É –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—ñ "–ë–∞—Ç–∞–ª—å–π–æ–Ω A".  
‚úÖ **–ó–∞–≤–¥–∞–Ω–Ω—è 2:** –í–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É—é—á–∏ `JOIN`, –æ—Ç—Ä–∏–º–∞—Ç–∏ —Å–ø–∏—Å–æ–∫ –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö —Ä–∞–∑–æ–º —ñ–∑ –Ω–∞–∑–≤–∞–º–∏ –ø—ñ–¥—Ä–æ–∑–¥—ñ–ª—ñ–≤.  
‚úÖ **–ó–∞–≤–¥–∞–Ω–Ω—è 3:** –í–∏–∫–æ–Ω–∞—Ç–∏ –∑–∞–ø–∏—Ç MongoDB –¥–ª—è –≤–∏–≤–æ–¥—É –≤—Å—ñ—Ö –≤—ñ–π—Å—å–∫–æ–≤–∏—Ö, —è–∫—ñ –º–∞—é—Ç—å –∑–≤–∞–Ω–Ω—è "–ö–∞–ø—ñ—Ç–∞–Ω".  
‚úÖ **–ó–∞–≤–¥–∞–Ω–Ω—è 4:** –ü–æ—Ä—ñ–≤–Ω—è—Ç–∏ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–∏ –≤–∏–±—ñ—Ä–∫–∏ –º—ñ–∂ SQL —Ç–∞ MongoDB.  

üìå **–ü—Ä–∏–∫–ª–∞–¥ –≤–∏–∫–æ–Ω–∞–Ω–Ω—è –∑–∞–≤–¥–∞–Ω–Ω—è 1:**  
```sql
SELECT full_name FROM Personnel WHERE unit_id = (SELECT unit_id FROM Units WHERE name = '–ë–∞—Ç–∞–ª—å–π–æ–Ω A');
```
üìå **–ü—Ä–∏–∫–ª–∞–¥ –≤–∏–∫–æ–Ω–∞–Ω–Ω—è –∑–∞–≤–¥–∞–Ω–Ω—è 3:**  
```javascript
db.personnel.find({ "rank": "–ö–∞–ø—ñ—Ç–∞–Ω" })
```

---

## **5. –í–∏—Å–Ω–æ–≤–∫–∏ —Ç–∞ –ø—ñ–¥—Å—É–º–∫–∏ –ª–µ–∫—Ü—ñ—ó (10 —Ö–≤)**  

‚úÖ **–û—Å–Ω–æ–≤–Ω—ñ –≤–∏—Å–Ω–æ–≤–∫–∏**:
- SQL –¥–æ–∑–≤–æ–ª—è—î –≤–∏–∫–æ–Ω—É–≤–∞—Ç–∏ —Å–∫–ª–∞–¥–Ω—ñ –≤–∏–±—ñ—Ä–∫–∏ –¥–∞–Ω–∏—Ö –∑–∞ –¥–æ–ø–æ–º–æ–≥–æ—é `SELECT`, `JOIN`, `WHERE`, `GROUP BY`.
- MongoDB –∑–∞–±–µ–∑–ø–µ—á—É—î –≥–Ω—É—á–∫—É –æ–±—Ä–æ–±–∫—É –¥–∞–Ω–∏—Ö —É JSON-–ø–æ–¥—ñ–±–Ω–æ–º—É —Ñ–æ—Ä–º–∞—Ç—ñ.
- –í–∏–±—ñ—Ä –º—ñ–∂ SQL —Ç–∞ NoSQL –∑–∞–ª–µ–∂–∏—Ç—å –≤—ñ–¥ —Å–ø–µ—Ü–∏—Ñ—ñ–∫–∏ –∑–∞—Å—Ç–æ—Å—É–≤–∞–Ω–Ω—è.

üöÄ **–ö–ª—é—á–æ–≤–∏–π –º–µ—Å–µ–¥–∂**:  
**–í–∏–±—ñ—Ä —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—ó –∑ –±–∞–∑–∏ –¥–∞–Ω–∏—Ö —î –∫–ª—é—á–æ–≤–∏–º –ø—Ä–æ—Ü–µ—Å–æ–º —É –≤—ñ–π—Å—å–∫–æ–≤—ñ–π –∞–Ω–∞–ª—ñ—Ç–∏—Ü—ñ. –í–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è —Ä–µ–ª—è—Ü—ñ–π–Ω–∏—Ö —Ç–∞ –Ω–µ—Ä–µ–ª—è—Ü—ñ–π–Ω–∏—Ö –±–∞–∑ –¥–∞–Ω–∏—Ö –¥–∞—î –º–æ–∂–ª–∏–≤—ñ—Å—Ç—å –µ—Ñ–µ–∫—Ç–∏–≤–Ω–æ–≥–æ —É–ø—Ä–∞–≤–ª—ñ–Ω–Ω—è –¥–∞–Ω–∏–º–∏ —É —Å–∫–ª–∞–¥–Ω–∏—Ö —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ–π–Ω–∏—Ö —Å–∏—Å—Ç–µ–º–∞—Ö.**